### ISSUE TITLE
Get rid of Netlify logout button right after signing up/login

### ISSUE THREAD

**Issue by glrta** [fac19/teach-fish-frontend#31]
Can we change that?

**Comment by akomiqaia** [comment]
i had a look on google and on netlify doc but could not find any solution. Looks like redirect can be a solution. I tried to put in your code but was not sure where i could put it. https://github.com/netlify/netlify-cms/issues/2031 . also noticed that on netlify widget docs there is function netlify.close() or something that closes the modal. Not sure if it works but maybe if you have logic that checks JWT and if exists just close the modal? The second option might be very wrong and i guess you can think of redirecting immediately after logging in.

**Comment by Chloeh24** [comment]
Apparently this is a built in thing on netlify and can't be changed and, according to [this chat](https://github.com/netlify/netlify-identity-widget/issues/85), they're not going to change it. The only solution they offered was to use something called [Go True](https://github.com/netlify/gotrue-js) instead :confused:

**Comment by akomiqaia** [comment]
Yeap looks like it but redirects works for sure. if you login on netlify and manually refresh the page the modal classes so what you can do after logging in refresh the page again to remove the modal.

**Comment by hannahgooding** [comment]
Thank you for the suggestions we will try these!
