### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Roger-Heathcote** [fac19/teach-fish-frontend#33]
It's great that you've got plenty of snapshot tests so you know if anything breaks quickly. Moving forward it would be good to see some unit tests for any blocks of logic you create and some E2E/integration testing for your user stories/journeys. We have had some good results using Cypress for the latter. Kat has made a spike on installing and configuring it that might be useful: https://www.notion.so/Cypress-325f87c9d7c3466f82c59062e0fd07c2

**Comment by hannahgooding** [comment]
@Roger-Heathcote please could you send this on a HACKMD as your Notion is private
